title: Lucy Evans
description: PhD Candidate in Microbiology | University of Birmingham
remote_theme: pages-themes/cayman@v0.2.0

# Language and encoding for better SEO
lang: en-GB
encoding: utf-8

include:
  - assets
  - _data 
  - "*.html"
  - "*.tsv"
  - "*.png"
